services:
  - type: web
    name: wuzen-x
    runtime: docker
    dockerfilePath: server/src/Dockerfile
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: RENDER_URL
        sync: false
      - key: BASE_APK_URL
        sync: false
      - key: SERVER_URL
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: KEYSTORE_BASE64
        sync: false
      - key: KEYSTORE_PASS
        sync: false
      - key: KEY_ALIAS
        sync: false
      - key: DEBUG
        value: "1"
